export { AboutPage } from './about-page'
export { ContactPage } from './contact-page'
export { ErrorPage } from './error-page'
export { LandingPage } from './landing-page'
export { LocationsPage } from './locations-page'
export { MenusPage } from './menus-page'
